FROM httpd:2.4

#COPY dev-insecure-cert.pem /etc/ssl/certs/insecure.pem
#COPY dev-insecure-cert.key /etc/ssl/private/insecure.key
#
#COPY httpd.conf /usr/local/apache2/conf/httpd.conf
#
#RUN mkdir sites/domain_*.conf /usr/local/apache2/conf.d/

